 INFO 30 八月 20:18:48,890 -(              MoDBRW.java: 132) - execSQL: select monet_id,type_id from Equipment where monet_id in (select distinct monetid   from user_event  where server_date > ? and server_date < ? ) =3089
 INFO 30 八月 20:18:49,484 -(              MoDBRW.java: 132) - execSQL: select id,type from EquipmentType =531
 INFO 30 八月 20:18:50,435 -(              MoDBRW.java: 132) - execSQL: select ownerid,petLevel from pet =936
 INFO 30 八月 20:18:51,528 -(              MoDBRW.java: 132) - execSQL: select monet_id,type_id from Equipment where expire_date > ?  =1061
 INFO 30 八月 20:18:51,748 -(              MoDBRW.java: 132) - execSQL: select id,type from EquipmentType =172
 INFO 30 八月 20:18:52,325 -(              MoDBRW.java: 132) - execSQL: select ownerid,petLevel from pet =562
 INFO 30 八月 20:22:14,021 -(              MoDBRW.java: 132) - execSQL: select monet_id,type_id from Equipment where monet_id in (select distinct monetid   from user_event  where server_date > ? and server_date < ? ) =2340
 INFO 30 八月 20:22:14,677 -(              MoDBRW.java: 132) - execSQL: select id,type from EquipmentType =593
 INFO 30 八月 20:22:15,519 -(              MoDBRW.java: 132) - execSQL: select ownerid,petLevel from pet =826
ERROR 30 八月 20:22:16,581 -(              MoDBRW.java: 229) - execSQLUpdate error
com.microsoft.sqlserver.jdbc.SQLServerException: 到主机  的 TCP/IP 连接失败。 java.net.ConnectException: Connection refused: connect
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.loginWithoutFailover(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:46)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:290)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:771)
	at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:175)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at util.MoDB.getConnection(MoDB.java:54)
	at util.MoDBRW.execSQLUpdate(MoDBRW.java:219)
	at petEquiment.PetEquiment.insertinto(PetEquiment.java:221)
	at petEquiment.PetEquiment.insertEquipment(PetEquiment.java:207)
	at petEquiment.PetEquiment.main(PetEquiment.java:230)
 INFO 30 八月 20:22:16,581 -(              MoDBRW.java: 234) - execSQLUpdate: insert into EquipmentInventory(petLevel,equimentType,equimentCount,equimentPerson,rdate,isAction)values(?,?,?,?,?,?) =1029
ERROR 30 八月 20:22:17,596 -(              MoDBRW.java: 229) - execSQLUpdate error
com.microsoft.sqlserver.jdbc.SQLServerException: 到主机  的 TCP/IP 连接失败。 java.net.ConnectException: Connection refused: connect
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.loginWithoutFailover(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:46)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:290)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:771)
	at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:175)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at util.MoDB.getConnection(MoDB.java:54)
	at util.MoDBRW.execSQLUpdate(MoDBRW.java:219)
	at petEquiment.PetEquiment.insertinto(PetEquiment.java:221)
	at petEquiment.PetEquiment.insertEquipment(PetEquiment.java:207)
	at petEquiment.PetEquiment.main(PetEquiment.java:230)
 INFO 30 八月 20:22:17,596 -(              MoDBRW.java: 234) - execSQLUpdate: insert into EquipmentInventory(petLevel,equimentType,equimentCount,equimentPerson,rdate,isAction)values(?,?,?,?,?,?) =1015
ERROR 30 八月 20:22:18,611 -(              MoDBRW.java: 229) - execSQLUpdate error
com.microsoft.sqlserver.jdbc.SQLServerException: 到主机  的 TCP/IP 连接失败。 java.net.ConnectException: Connection refused: connect
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.loginWithoutFailover(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:46)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:290)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:771)
	at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:175)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at util.MoDB.getConnection(MoDB.java:54)
	at util.MoDBRW.execSQLUpdate(MoDBRW.java:219)
	at petEquiment.PetEquiment.insertinto(PetEquiment.java:221)
	at petEquiment.PetEquiment.insertEquipment(PetEquiment.java:207)
	at petEquiment.PetEquiment.main(PetEquiment.java:230)
 INFO 30 八月 20:22:18,611 -(              MoDBRW.java: 234) - execSQLUpdate: insert into EquipmentInventory(petLevel,equimentType,equimentCount,equimentPerson,rdate,isAction)values(?,?,?,?,?,?) =1015
ERROR 30 八月 20:22:19,626 -(              MoDBRW.java: 229) - execSQLUpdate error
com.microsoft.sqlserver.jdbc.SQLServerException: 到主机  的 TCP/IP 连接失败。 java.net.ConnectException: Connection refused: connect
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.loginWithoutFailover(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:46)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:290)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:771)
	at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:175)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at util.MoDB.getConnection(MoDB.java:54)
	at util.MoDBRW.execSQLUpdate(MoDBRW.java:219)
	at petEquiment.PetEquiment.insertinto(PetEquiment.java:221)
	at petEquiment.PetEquiment.insertEquipment(PetEquiment.java:207)
	at petEquiment.PetEquiment.main(PetEquiment.java:230)
 INFO 30 八月 20:22:19,626 -(              MoDBRW.java: 234) - execSQLUpdate: insert into EquipmentInventory(petLevel,equimentType,equimentCount,equimentPerson,rdate,isAction)values(?,?,?,?,?,?) =1015
